# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Honbabhanyang' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'

  # Pods for Honbabhanyang

  target 'HonbabhanyangTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HonbabhanyangUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
